version: "3"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATA_MONGODB_DATABASE: EnterpriseArchElectronics
      SPRING_DATA_MONGODB_URI: mongodb+srv://JonathanP:adminPassword@cluster0.xrps5.mongodb.net/EnterpriseArchElectronics?retryWrites=true&w=majority