server:
  port: 8080
spring:
  application:
    name: "EnterpriseArchElectronics"
  devtools:
    add-properties: false
  h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
    include: null
  data:
    mongodb:
      uri: "mongodb+srv://JonathanP:adminPassword@cluster0.xrps5.mongodb.net/EnterpriseArchElectronics?retryWrites=true&w=majority"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
springdoc:
  swagger-ui:
    path: /api/electronics-store/swagger-ui.html